const API_KEY = process.env.REACT_APP_KEY_FUNCTIONS;
const URL_API = process.env.REACT_APP_ENDPONT_FUNCTIONS;
const CLIENT_ID_MICROSOFT_AD = process.env.REACT_APP_CLIENT_ID_MICROSOFT_AD;
const AUTHORITY_ENDPOINT_MICROSOFT_AD = process.env.REACT_APP_AUTHORITY_ENDPOINT_MICROSOFT_AD;
const GRAPH_ENDPOINT_MICROSOFT_AD = process.env.REACT_APP_GRAPH_ENDPOINT_MICROSOFT_AD;
const SPEECH_TEXT_URL_TOKEN = process.env.REACT_APP_SPEECH_TEXT_URL_TOKEN;
const SPEECH_TEXT_URL_SERVICE = process.env.REACT_APP_SPEECH_TEXT_URL_SERVICE;
const SPEECH_TEXT_KEY = process.env.REACT_APP_SPEECH_TEXT_KEY;
const TEXT_ANALYSIS_URL = process.env.REACT_APP_TEXT_ANALYSIS_URL;
const TEXT_ANALYSIS_KEY= process.env.REACT_APP_TEXT_ANALYSIS_KEY;

export {
    API_KEY,
    URL_API,
    CLIENT_ID_MICROSOFT_AD,
    GRAPH_ENDPOINT_MICROSOFT_AD,
    AUTHORITY_ENDPOINT_MICROSOFT_AD,
    SPEECH_TEXT_URL_TOKEN,
    SPEECH_TEXT_URL_SERVICE,
    SPEECH_TEXT_KEY,
    TEXT_ANALYSIS_URL,
    TEXT_ANALYSIS_KEY
}